### ISSUE TITLE
models/user/Users.js getProject()

### ISSUE THREAD

**Issue by bilgincan** [usersmagic/usersmagic_landing_page#8]
Localimde çalıştırırken, buradan bana compiler hatası attı, sonrasında const getProject = require('../project/getProject'); yazınca çalıştı. Normalde bu ekstradan yazdığım satır orada olmalı mı, o değişikliği pushlayayım mı, yoksa bu hali şuan çalışıyor mu?

**Comment by yunus433** [comment]
Yanlış bir fonksiyon kullanılmış. Orayı tamamen sildim zaten gerek olmadığı için.
